----------------------------------
--PASOS PREVIOS-------------------
----------------------------------
----------------------------------

CREATE TABLESPACE NEMO
DATAFILE
  'C:\ORACLE\EJEMPLOS\NEMO\NEMO-1.ORA' 1 M,
  'C:\ORACLE\EJEMPLOS\NEMO\NEMO-2.ORA' 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER NEMO IDENTIFIED BY NEMO
DEFAULT TABLESPACE NEMO;
COMMIT;
GRANT DBA NEMO;
COMMIT;
GRANT CONNECT TO NEMO;
COMMIT;
CONNECT NEMO;

------------------------------------
--CREACIÓN TABLAS-------------------
------------------------------------
------------------------------------

CREATE TABLE EQUIPOS
(
CODIGO NUMBER(10), 
NOMBRE VARCHAR2(50),
ESTADIO VARCHAR2(50),
AFORO NUMBER(10),
CIUDAD VARCHAR2(50),
ANYOFUN DATE,
CONSTRAINT PK_EQUIPOS PRIMARY KEY (CODIGO)
);
COMMIT;

CREATE TABLE PRESIDENTES
(
DNI VARCHAR2(50),
NOMBRE VARCHAR2(50),
APELLIDOS VARCHAR2(50),
FECHAELE DATE,
FECHANAC DATE,
CODIGOEQUIPO NUMBER(10),
CONSTRAINT PK_PRESIDENTES PRIMARY KEY (DNI),
CONSTRAINT FK_PRESIDENTES FOREIGN KEY (CODIGOEQUIPO) REFERENCES EQUIPOS (CODIGO)
);
COMMIT;

CREATE TABLE JUGADORES
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(50),
FECHANAC DATE,
POSICION VARCHAR2(50),
CODIGOEQUIPO NUMBER(10),
CONSTRAINT PK_JUGADORES PRIMARY KEY (CODIGO),
CONSTRAINT FK_JUGADORES FOREIGN KEY (CODIGOEQUIPO) REFERENCES EQUIPOS (CODIGO),

CONSTRAINT CK_JUGADORES CHECK (POSICION IN ('Portero', 'Defensa', 'Centrocampista', 'Delantero')), --RESTRICCIÓN 3: La posición de un portero...
CONSTRAINT CK2_JUGADORES CHECK (FECHANAC BETWEEN 2002 AND 99999), --RESTRICCIÓN 4: Los jugadores deben tener mínimo 16 años
);
COMMIT;

CREATE TABLE PARTIDOS
(
CODIGO NUMBER(10),
FECHA DATE CONSTRAINT NN_PARTIDOS NOT NULL, --RESTRICCIÓN 5: La fecha de un partido es un campo obligatorio
CODEQUIVIS NUMBER(10),
CODEQUILOC NUMBER(10),
CONSTRAINT PK_PARTIDOS PRIMARY KEY (CODIGO),
CONSTRAINT FK_PARTIDOS FOREIGN KEY (CODEQUIVIS) REFERENCES EQUIPOS (CODIGO),
CONSTRAINT FK2_PARTIDOS FOREIGN KEY (CODEQUILOC) REFERENCES EQUIPOS (CODIGO),

CONSTRAINT CK_PARTIDOS CHECK (FECHA NOT BETWEEN 21/06 AND 21/09) --RESTRICCIÓN 1: No hay partidos en verano
);
COMMIT;

CREATE TABLE GOLES
(
CODPARTIDO NUMBER(10),
CODJUGADOR NUMBER(10),
MINUTO NUMBER(10),
DESCRIPCION VARCHAR2(50),
CONSTRAINT PK_GOLES PRIMARY KEY (CODPARTIDO, CODJUGADOR, MINUTO),
CONSTRAINT FK_GOLES FOREIGN KEY (CODPARTIDO) REFERENCES PARTIDOS (CODIGO),
CONSTRAINT FK2_GOLES FOREIGN KEY (CODJUGADOR) REFERENCES JUGADORES (CODIGO),

CONSTRAINT CK_GOLES CHECK (MINUTO BETWEEN 0 AND 100) --RESTRICCIÓN 2: Los partidos no pueden durar más de 100 minutos

);
COMMIT;


----------------------------------
--ALTER TABLES--------------------
----------------------------------
----------------------------------

ALTER TABLE EQUIPOS ADD NUMTITULOS NUMBER(10);
ALTER TABLE EQUIPOS DROP CIUDAD;
ALTER TABLE EQUIPOS ADD CONSTRAINT CK_EQUIPOS CHECK (ANYOFUN BETWEEN 1890 AND 99999);
ALTER TABLE PARTIDOS ADD CONSTRAINT CK2_PARTIDOS CHECK (DATE BETWEEN 12:00 AND 22:00);