--INSERCIÓN A JUGADORES

INSERT INTO JUGADORES
VALUES(1, 'Iker Casillas', TO_DATE('05-06-1980', 'DD-MM-YYYY'), 'Portero', 1);

INSERT INTO JUGADORES
VALUES(2, 'Ronaldo', TO_DATE('07-07-1984', 'DD-MM-YYYY'), 'Delantero', 1);

INSERT INTO JUGADORES
VALUES(3, 'Zidedine Zidane', TO_DATE('06-06-1968', 'DD-MM-YYYY'), 'Centrocampista', 1);

INSERT INTO JUGADORES
VALUES(4, 'Samuel Etoo', TO_DATE('03-03-1976', 'DD-MM-YYYY'), 'Delantero', 2);

INSERT INTO JUGADORES
VALUES(5, 'Ronaldinho', TO_DATE('05-05-1979', 'DD-MM-YYYY'), 'Centrocampista', 2);

INSERT INTO JUGADORES
VALUES(6, 'Deco', TO_DATE('03-03-1976', 'DD-MM-YYYY'), 'Centrocampista', 2);

INSERT INTO JUGADORES
VALUES(7, 'Baraja', TO_DATE('05-05-1975', 'DD-MM-YYYY'), 'Centrocampista', 3);

INSERT INTO JUGADORES
VALUES(8, 'Albeda', TO_DATE('03-03-1973', 'DD-MM-YYYY'), 'Centrocampista', 3);

INSERT INTO JUGADORES
VALUES(9, 'Aimar', TO_DATE('05-05-1975', 'DD-MM-YYYY'), 'Centrocampista', 3);

INSERT INTO JUGADORES
VALUES(10, 'Vicente', TO_DATE('06-05-1976', 'DD-MM-YYYY'), 'Centrocampista', 3);

--INSERCIÓN A EQUIPOS

INSERT INTO EQUIPOS
VALUES(1, 'Real Madrid', 'Santiago Bernabeu', 80000, TO_DATE('1950', 'YYYY'), 'Madrid');

INSERT INTO EQUIPOS
VALUES(2, 'F.C. Barcelona', 'Camp Nou', 70000, TO_DATE('1948', 'YYYY'), 'Barcelona');

INSERT INTO EQUIPOS
VALUES(3, 'Valencia C.F', 'Mestalla', 60000, TO_DATE('1952', 'YYYY'), 'Valencia');

INSERT INTO EQUIPOS
VALUES(4, 'Atlético de Madrid', 'Vicente Calderón', 55000, TO_DATE('1945', 'YYYY'), 'Madrid');

--INSERCIÓN A PARTIDOS

INSERT INTO PARTIDOS
VALUES(1, TO_DATE('03-03-1905', 'DD-MM-YYYY'), 2, 1);

INSERT INTO PARTIDOS
VALUES(2, TO_DATE('04-04-1905', 'DD-MM-YYYY'), 3, 1);

INSERT INTO PARTIDOS
VALUES(3, TO_DATE('03-04-1905', 'DD-MM-YYYY'), 2, 4);

--INSERCIÓN A GOLES

INSERT INTO GOLES
VALUES(1, 2, 35, 'De falta');

INSERT INTO GOLES
VALUES(1, 2, 70, '');

--INSERT INTO GOLES
--VALUES(1, 2, 70, NULL); ES OTRA FORMA DE PONER LOS VACÍOS

INSERT INTO GOLES
VALUES(1, 4, 88, '');

INSERT INTO GOLES
VALUES(1, 3, 5, '');

INSERT INTO GOLES
VALUES(1, 2, 10, 'De penalti');

INSERT INTO GOLES
VALUES(1, 3, 47, '');

INSERT INTO GOLES
VALUES(1, 7, 60, '');

INSERT INTO GOLES
VALUES(2, 9, 8, '');

INSERT INTO GOLES
VALUES(2, 9, 9, '');

INSERT INTO GOLES
VALUES(2, 7, 50, 'De penalti');

INSERT INTO GOLES
VALUES(2, 7, 65, '');