CREATE TABLESPACE PINACOTECAS
DATAFILE
  'C:\ORACLE\EJEMPLOS\PINACOTECAS\PINACOTECAS-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\PINACOTECAS\PINACOTECAS-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER PINACOTECAS
IDENTIFIED BY PINACOTECAS
DEFAULT TABLESPACE PINACOTECAS
QUOTA UNLIMITED ON PINACOTECAS;
COMMIT;
GRANT DBA TO PINACOTECAS;
COMMIT;
CONNECT PINACOTECAS;