-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 13:48:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather_station` DEFAULT CHARACTER SET utf8 ;
USE `weather_station` ;

-- -----------------------------------------------------
-- Table `weather_station`.`estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`estaciones` (
  `id` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `ip` CHAR(15) NULL,
  `tipo_conex` VARCHAR(45) NULL,
  `ubi` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather_station`.`sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`sensores` (
  `id` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `desc` VARCHAR(255) NULL,
  `id_estacion` INT NOT NULL,
  PRIMARY KEY (`id`, `id_estacion`),
  CONSTRAINT `fk_sensores_estaciones1`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `weather_station`.`estaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather_station`.`variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`variables` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ud_med` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather_station`.`asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`asignaciones` (
  `id_sensor` INT NOT NULL,
  `id_variable` INT NOT NULL,
  PRIMARY KEY (`id_sensor`, `id_variable`),
  CONSTRAINT `fk_Sensores_has_Variables meteorológicas_Sensores1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `weather_station`.`sensores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sensores_has_Variables meteorológicas_Variables meteorol1`
    FOREIGN KEY (`id_variable`)
    REFERENCES `weather_station`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather_station`.`medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`medidas` (
  `id_sensor` INT NOT NULL,
  `id_variable` INT NOT NULL,
  `fecha_hora` TIMESTAMP NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_sensor`, `id_variable`, `fecha_hora`),
  CONSTRAINT `fk_Sensores_has_Variables meteorológicas1_Sensores1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `weather_station`.`sensores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sensores_has_Variables meteorológicas1_Variables meteorol1`
    FOREIGN KEY (`id_variable`)
    REFERENCES `weather_station`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
