--HECHO POR ADRIÁN JARAMILLO RODRÍGUEZ--

CREATE TABLE PERSONAL
(
PASAPORTE NUMBER(20),
NOMBRE VARCHAR2(50),
TELEFONO NUMBER(20),
DIRECCION VARCHAR2(50),
ANTIGUEDAD NUMBER(2),
HORAS_EXTRA NUMBER(6),
SUELDO_BASE NUMBER(6),
TIPO VARCHAR2(10),
CONSTRAINT pk_personal PRIMARY KEY (PASAPORTE)
);
COMMIT;

CREATE TABLE AEROPUERTOS 
(
NOMBRE VARCHAR2(50),
DIRECCION VARCHAR2(50),
TELEFONO NUMBER(20),
DIRECTOR VARCHAR2(50),
N_PISTAS NUMBER(10),
VOL_TRAF NUMBER(10),
CIUDADCERCANA VARCHAR2(50),
CONSTRAINT pk_aeropuertos PRIMARY KEY (NOMBRE)
);
COMMIT;

CREATE TABLE COMPANYA 
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(50),
CONSTRAINT pk_companya PRIMARY KEY (CODIGO)
);
COMMIT;

CREATE TABLE PASAJEROS 
(
PASAPORTE NUMBER(20),
NOMBRE VARCHAR2(50),
CONSTRAINT pk_pasajeros PRIMARY KEY (PASAPORTE)
);
COMMIT;

CREATE TABLE AUXS_VUELS
(
PAS_AUX NUMBER(20),
COMPANYA VARCHAR2(20),
VUELO NUMBER(10),
ORIGEN VARCHAR2(50),
FECHA DATE,
CONSTRAINT pk_auxs_vuels PRIMARY KEY (PAS_AUX, COMPANYA, VUELO, ORIGEN, FECHA),
CONSTRAINT fk1_auxs_vuels FOREIGN KEY (PAS_AUX) REFERENCES PERSONAL (PASAPORTE),
CONSTRAINT fk2_auxs_vuels FOREIGN KEY (COMPANYA, VUELO, ORIGEN) REFERENCES VUELOS (COMPANYA, VUELO, ORIGEN)
);
COMMIT;

CREATE TABLE VUELOS 
(
COMPANYA VARCHAR2(20),
VUELO NUMBER(10),
ORIGEN VARCHAR2(50),
DESTINO VARCHAR2(50),
HORARIO NUMBER(6),
PAS_PILOTO NUMBER(20),
PAS_COPILOTO NUMBER(20),
N_AE_LLEGA VARCHAR2(50),
N_AE_SALE VARCHAR2(50),
FECHA DATE,
N_SERIE_AVION NUMBER(10),
CONSTRAINT pk_vuelos PRIMARY KEY (COMPANYA, VUELO, ORIGEN),
CONSTRAINT fk1_vuelos FOREIGN KEY (PAS_PILOTO) REFERENCES PERSONAL (PASAPORTE),
CONSTRAINT fk2_vuelos FOREIGN KEY (PAS_COPILOTO) REFERENCES PERSONAL (PASAPORTE),
CONSTRAINT fk3_vuelos FOREIGN KEY (N_AE_LLEGA) REFERENCES AEROPUERTOS (NOMBRE),
CONSTRAINT fk4_vuelos FOREIGN KEY (N_AE_SALE) REFERENCES AEROPUERTOS (NOMBRE),
CONSTRAINT fk5_vuelos FOREIGN KEY (N_SERIE_AVION) REFERENCES AVIONES (N_SERIE)
);
COMMIT;

CREATE TABLE AVIONES 
(
N_SERIE NUMBER(10),
ANTIGÜEDAD NUMBER(2),
HORAS_VUELO NUMBER(5),
F_REV DATE,
CARACTER VARCHAR2(50),
COD_COMP NUMBER(10),
CONSTRAINT pk_aviones PRIMARY KEY (N_SERIE),
CONSTRAINT fk_aviones FOREIGN KEY (COD_COMP) REFERENCES COMPANYA (CODIGO)
);
COMMIT;

CREATE TABLE PAS_TOM_VUE 
(
COMPANYA VARCHAR2(20),
VUELO NUMBER(10),
ORIGEN VARCHAR2(50),
FECHA DATE,
N_BULTOS NUMBER(5),
P_EQUIPAJE NUMBER(6),
PAS_PASAJERO NUMBER(20),
CONSTRAINT pk_pas_tom_vue PRIMARY KEY (COMPANYA, VUELO, ORIGEN, FECHA, PAS_PASAJERO),
CONSTRAINT fk1_pas_tom_vue FOREIGN KEY (COMPANYA, VUELO, ORIGEN) REFERENCES VUELOS (COMPANYA, VUELO, ORIGEN),
CONSTRAINT fk2_pas_tom_vue FOREIGN KEY (PAS_PASAJERO) REFERENCES PASAJEROS (PASAPORTE)
);
COMMIT;













