CREATE TABLESPACE VUELOS
DATAFILE
  'C:\ORACLE\EJEMPLOS\VUELOS\VUELOS-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\VUELOS\VUELOS-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER VUELOS
IDENTIFIED BY VUELOS
DEFAULT TABLESPACE VUELOS
QUOTA UNLIMITED ON VUELOS;
COMMIT;
GRANT DBA TO VUELOS;
COMMIT;
CONNECT VUELOS;